import { Database } from '@nozbe/watermelondb';
import { Festival, FestivalTrigger } from '../models/Festival';

// ── Safety Score Algorithm ────────────────────────────────────────────────────
// Computed at seed time. 0–99. Higher = safer signal environment.

const COUNTRY_SCORES: Record<string, number> = {
  UK: 15,
  Australia: 12,
  Germany: 12,
  Netherlands: 12,
  Belgium: 10,
  France: 8,
  Spain: 8,
  Italy: 8,
  Portugal: 8,
  Croatia: 5,
  Hungary: 5,
  Romania: 0,
  USA: 0,
  Thailand: 0,
};

function computeSafetyScore(country: string, attendance: number, camping: boolean): number {
  let score = 75;
  score += COUNTRY_SCORES[country] ?? 0;
  if (attendance >= 400_000) score -= 20;
  else if (attendance >= 200_000) score -= 15;
  else if (attendance >= 100_000) score -= 10;
  else if (attendance >= 50_000) score -= 5;
  if (camping) score += 3;
  return Math.max(15, Math.min(99, score));
}

function inferTrigger(vibe: string, camping: boolean): FestivalTrigger {
  const v = vibe.toLowerCase();
  if (v.includes('water') || v.includes('wet')) return 'wet';
  if (v.includes('beach') || v.includes('surf')) return 'beach';
  return 'none';
}

// ── Embedded CSV Data ─────────────────────────────────────────────────────────

interface RawFestival {
  name: string;
  city: string;
  country: string;
  startDate: string;
  endDate: string;
  lat: number;
  lng: number;
  vibe: string;
  camping: boolean;
  attendance: number;
  language: string;
  medicalDoctor: string;
  medicalAllergy: string;
  legalFreeToGo: string;
  legalCallEmbassy: string;
  scriptLostSquad: string;
  scriptSubstance: string;
  scriptMedicalTent: string;
  scriptCharging: string;
}

const CSV_FESTIVALS: RawFestival[] = [
  {
    name: 'EDC Thailand', city: 'Phuket', country: 'Thailand',
    startDate: '2026-01-16', endDate: '2026-01-18', lat: 8.001, lng: 98.306,
    vibe: 'Neon EDM', camping: false, attendance: 50_000, language: 'Thai',
    medicalDoctor: 'ฉันต้องการหมอ (Chǎn dtâung-gaan mǎu)',
    medicalAllergy: 'ฉันแพ้ยาเพนิซิลลิน (Chǎn pháe yaa pay-nee-sil-lin)',
    legalFreeToGo: 'ฉันไปได้หรือยัง? (Chǎn bpai dâai rǔu yang?)',
    legalCallEmbassy: 'ฉันต้องการโทรหาสถานทูต (Chǎn dtâung-gaan tō hǎa sà-thǎan-thôot)',
    scriptLostSquad: 'ฉันหลงกับเพื่อน ขอใช้โทรศัพท์หรือไวไฟได้ไหม (Chǎn lǒng gàp pêuuan. Kǎu chái tō-rá-sàp rǔu wai-fai dâai mǎi?)',
    scriptSubstance: 'เพื่อนฉันกินบางอย่างเข้าไปและต้องการความช่วยเหลือ โปรดอย่าเรียกตำรวจ (Pêuuan chǎn gin baang yàang khâo bpai... bpròat yàa rîak dtam-rùat)',
    scriptMedicalTent: 'เต็นท์พยาบาล / โซนสวัสดิการ อยู่ที่ไหน (Dten phá-yaa-baan / sōn sà-wàt-dì-gaan yùu thîe nǎi?)',
    scriptCharging: 'แบตโทรศัพท์กำลังจะหมด ที่ชาร์จอยู่ที่ไหน (Bàet tō-rá-sàp gam-lang jà mòt. Thîe cháat yùu thîe nǎi?)',
  },
  {
    name: 'UnKonscious', city: 'Pattaya', country: 'Thailand',
    startDate: '2026-02-05', endDate: '2026-02-08', lat: 12.825, lng: 100.912,
    vibe: 'Pure Trance', camping: false, attendance: 15_000, language: 'Thai',
    medicalDoctor: 'ฉันต้องการหมอ (Chǎn dtâung-gaan mǎu)',
    medicalAllergy: 'ฉันแพ้ยาเพนิซิลลิน (Chǎn pháe yaa pay-nee-sil-lin)',
    legalFreeToGo: 'ฉันไปได้หรือยัง? (Chǎn bpai dâai rǔu yang?)',
    legalCallEmbassy: 'ฉันต้องการโทรหาสถานทูต (Chǎn dtâung-gaan tō hǎa sà-thǎan-thôot)',
    scriptLostSquad: 'ฉันหลงกับเพื่อน ขอใช้โทรศัพท์หรือไวไฟได้ไหม (Chǎn lǒng gàp pêuuan. Kǎu chái tō-rá-sàp rǔu wai-fai dâai mǎi?)',
    scriptSubstance: 'เพื่อนฉันกินบางอย่างเข้าไปและต้องการความช่วยเหลือ โปรดอย่าเรียกตำรวจ (Pêuuan chǎn gin baang yàang khâo bpai... bpròat yàa rîak dtam-rùat)',
    scriptMedicalTent: 'เต็นท์พยาบาล / โซนสวัสดิการ อยู่ที่ไหน (Dten phá-yaa-baan / sōn sà-wàt-dì-gaan yùu thîe nǎi?)',
    scriptCharging: 'แบตโทรศัพท์กำลังจะหมด ที่ชาร์จอยู่ที่ไหน (Bàet tō-rá-sàp gam-lang jà mòt. Thîe cháat yùu thîe nǎi?)',
  },
  {
    name: 'A State of Trance', city: 'Rotterdam', country: 'Netherlands',
    startDate: '2026-02-27', endDate: '2026-02-28', lat: 51.894, lng: 4.482,
    vibe: 'Trance', camping: false, attendance: 40_000, language: 'Dutch',
    medicalDoctor: 'Ik heb een dokter nodig.',
    medicalAllergy: 'Ik ben allergisch voor penicilline.',
    legalFreeToGo: 'Ben ik vrij om te gaan?',
    legalCallEmbassy: 'Ik wil mijn ambassade bellen.',
    scriptLostSquad: 'Ik ben mijn vrienden kwijt. Mag ik je telefoon of wifi gebruiken?',
    scriptSubstance: 'Mijn vriend heeft iets gebruikt en heeft hulp nodig. Geen politie aub.',
    scriptMedicalTent: 'Waar is de EHBO / medische post?',
    scriptCharging: 'Mijn telefoon is bijna leeg. Waar is een oplaadpunt?',
  },
  {
    name: 'Pitch Music & Arts', city: 'Moyston', country: 'Australia',
    startDate: '2026-03-06', endDate: '2026-03-10', lat: -37.297, lng: 142.771,
    vibe: 'Techno/House', camping: true, attendance: 20_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Tomorrowland Winter', city: "Alpe d'Huez", country: 'France',
    startDate: '2026-03-21', endDate: '2026-03-28', lat: 45.091, lng: 6.068,
    vibe: 'Snow EDM', camping: false, attendance: 25_000, language: 'French',
    medicalDoctor: "J'ai besoin d'un médecin.",
    medicalAllergy: 'Je suis allergique à la pénicilline.',
    legalFreeToGo: 'Suis-je libre de partir ?',
    legalCallEmbassy: 'Je veux appeler mon ambassade.',
    scriptLostSquad: "J'ai perdu mes amis. Puis-je utiliser votre téléphone ou le Wi-Fi ?",
    scriptSubstance: "Mon ami a pris quelque chose et a besoin d'aide. Pas de police, s'il vous plaît.",
    scriptMedicalTent: "Où se trouve la tente médicale / l'espace bien-être ?",
    scriptCharging: 'Ma batterie est faible. Où se trouve la station de charge ?',
  },
  {
    name: 'Time Warp', city: 'Mannheim', country: 'Germany',
    startDate: '2026-03-21', endDate: '2026-03-21', lat: 49.479, lng: 8.484,
    vibe: 'Pure Techno', camping: false, attendance: 20_000, language: 'German',
    medicalDoctor: 'Ich brauche einen Arzt.',
    medicalAllergy: 'Ich bin allergisch gegen Penicillin.',
    legalFreeToGo: 'Darf ich gehen?',
    legalCallEmbassy: 'Ich möchte meine Botschaft anrufen.',
    scriptLostSquad: 'Ich habe meine Freunde verloren. Kann ich Ihr Telefon oder WLAN benutzen?',
    scriptSubstance: 'Mein Freund hat etwas genommen und braucht Hilfe. Bitte keine Polizei.',
    scriptMedicalTent: 'Wo ist das Sanitätszelt / der Welfare-Bereich?',
    scriptCharging: 'Ich brauche eine Ladestation.',
  },
  {
    name: 'Ultra Miami', city: 'Miami', country: 'USA',
    startDate: '2026-03-27', endDate: '2026-03-29', lat: 25.778, lng: -80.186,
    vibe: 'Mainstage EDM', camping: false, attendance: 170_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Coachella (W1)', city: 'Indio', country: 'USA',
    startDate: '2026-04-10', endDate: '2026-04-12', lat: 33.678, lng: -116.236,
    vibe: 'Boutique/Multi', camping: true, attendance: 125_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'S2O Songkran', city: 'Bangkok', country: 'Thailand',
    startDate: '2026-04-11', endDate: '2026-04-13', lat: 13.753, lng: 100.585,
    vibe: 'Water/EDM', camping: false, attendance: 60_000, language: 'Thai',
    medicalDoctor: 'ฉันต้องการหมอ (Chǎn dtâung-gaan mǎu)',
    medicalAllergy: 'ฉันแพ้ยาเพนิซิลลิน (Chǎn pháe yaa pay-nee-sil-lin)',
    legalFreeToGo: 'ฉันไปได้หรือยัง? (Chǎn bpai dâai rǔu yang?)',
    legalCallEmbassy: 'ฉันต้องการโทรหาสถานทูต (Chǎn dtâung-gaan tō hǎa sà-thǎan-thôot)',
    scriptLostSquad: 'ฉันหลงกับเพื่อน ขอใช้โทรศัพท์หรือไวไฟได้ไหม (Chǎn lǒng gàp pêuuan. Kǎu chái tō-rá-sàp rǔu wai-fai dâai mǎi?)',
    scriptSubstance: 'เพื่อนฉันกินบางอย่างเข้าไปและต้องการความช่วยเหลือ โปรดอย่าเรียกตำรวจ (Pêuuan chǎn gin baang yàang khâo bpai... bpròat yàa rîak dtam-rùat)',
    scriptMedicalTent: 'เต็นท์พยาบาล / โซนสวัสดิการ อยู่ที่ไหน (Dten phá-yaa-baan / sōn sà-wàt-dì-gaan yùu thîe nǎi?)',
    scriptCharging: 'แบตโทรศัพท์กำลังจะหมด ที่ชาร์จอยู่ที่ไหน (Bàet tō-rá-sàp gam-lang jà mòt. Thîe cháat yùu thîe nǎi?)',
  },
  {
    name: 'Ultra Australia', city: 'Melbourne', country: 'Australia',
    startDate: '2026-04-11', endDate: '2026-04-12', lat: -37.778, lng: 144.928,
    vibe: 'Mainstage EDM', camping: false, attendance: 40_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Coachella (W2)', city: 'Indio', country: 'USA',
    startDate: '2026-04-17', endDate: '2026-04-19', lat: 33.678, lng: -116.236,
    vibe: 'Boutique/Multi', camping: true, attendance: 125_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'EDC Las Vegas', city: 'Las Vegas', country: 'USA',
    startDate: '2026-05-15', endDate: '2026-05-17', lat: 36.272, lng: -115.010,
    vibe: 'Neon EDM', camping: true, attendance: 525_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Bearded Theory', city: 'Derbyshire', country: 'UK',
    startDate: '2026-05-21', endDate: '2026-05-24', lat: 52.747, lng: -1.652,
    vibe: 'Eclectic/Family', camping: true, attendance: 15_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Primavera Sound', city: 'Barcelona', country: 'Spain',
    startDate: '2026-06-04', endDate: '2026-06-06', lat: 41.411, lng: 2.224,
    vibe: 'Indie/Electronic', camping: false, attendance: 150_000, language: 'Spanish',
    medicalDoctor: 'Necesito un médico.',
    medicalAllergy: 'Soy alérgico a la penicilina.',
    legalFreeToGo: '¿Soy libre de irme?',
    legalCallEmbassy: 'Quiero llamar a mi embajada.',
    scriptLostSquad: 'He perdido a mis amigos. ¿Puedo usar su teléfono o Wi-Fi?',
    scriptSubstance: 'Mi amigo ha tomado algo y necesita ayuda. Sin policía, por favor.',
    scriptMedicalTent: '¿Dónde está la carpa médica o el área de bienestar?',
    scriptCharging: 'Mi teléfono se está agotando. ¿Dónde está la estación de carga?',
  },
  {
    name: 'Bonnaroo', city: 'Manchester', country: 'USA',
    startDate: '2026-06-11', endDate: '2026-06-14', lat: 35.474, lng: -86.085,
    vibe: 'Alternative/Rave', camping: true, attendance: 80_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Download Festival', city: 'Donington', country: 'UK',
    startDate: '2026-06-12', endDate: '2026-06-14', lat: 52.830, lng: -1.377,
    vibe: 'Rock/Metal', camping: true, attendance: 100_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Sónar', city: 'Barcelona', country: 'Spain',
    startDate: '2026-06-18', endDate: '2026-06-20', lat: 41.343, lng: 2.127,
    vibe: 'Cerebral/Techno', camping: false, attendance: 80_000, language: 'Spanish',
    medicalDoctor: 'Necesito un médico.',
    medicalAllergy: 'Soy alérgico a la penicilina.',
    legalFreeToGo: '¿Soy libre de irme?',
    legalCallEmbassy: 'Quiero llamar a mi embajada.',
    scriptLostSquad: 'He perdido a mis amigos. ¿Puedo usar su teléfono o Wi-Fi?',
    scriptSubstance: 'Mi amigo ha tomado algo y necesita ayuda. Sin policía, por favor.',
    scriptMedicalTent: '¿Dónde está la carpa médica o el área de bienestar?',
    scriptCharging: 'Mi teléfono se está agotando. ¿Dónde está la estación de carga?',
  },
  {
    name: 'Isle of Wight Festival', city: 'Newport', country: 'UK',
    startDate: '2026-06-18', endDate: '2026-06-21', lat: 50.708, lng: -1.284,
    vibe: 'Legends/Pop', camping: true, attendance: 50_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Parklife', city: 'Manchester', country: 'UK',
    startDate: '2026-06-20', endDate: '2026-06-21', lat: 53.535, lng: -2.253,
    vibe: 'Urban/Electronic', camping: false, attendance: 80_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Glastonbury (Fallow Year)', city: 'Pilton', country: 'UK',
    startDate: '2026-06-24', endDate: '2026-06-28', lat: 51.155, lng: -2.585,
    vibe: 'Legends/Multi', camping: true, attendance: 210_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Hideout', city: 'Novalja', country: 'Croatia',
    startDate: '2026-06-30', endDate: '2026-07-03', lat: 44.558, lng: 14.887,
    vibe: 'Beach Party', camping: false, attendance: 25_000, language: 'Croatian',
    medicalDoctor: 'Trebam liječnika.',
    medicalAllergy: 'Alergičan sam na penicilin.',
    legalFreeToGo: 'Mogu li ići?',
    legalCallEmbassy: 'Želim nazvati svoje veleposlanstvo.',
    scriptLostSquad: 'Izgubio sam prijatelje. Mogu li koristiti vaš telefon ili Wi-Fi?',
    scriptSubstance: 'Moj prijatelj je nešto uzeo i treba mu pomoć. Bez policije, molim.',
    scriptMedicalTent: 'Gdje je medicinski šator / zona za dobrobit?',
    scriptCharging: 'Mobitel mi je prazan. Gdje je stanica za punjenje?',
  },
  {
    name: 'Hideout Festival', city: 'Pag Island', country: 'Croatia',
    startDate: '2026-06-30', endDate: '2026-07-03', lat: 44.558, lng: 14.887,
    vibe: 'Beach Party', camping: false, attendance: 25_000, language: 'Croatian',
    medicalDoctor: 'Trebam liječnika.',
    medicalAllergy: 'Alergičan sam na penicilin.',
    legalFreeToGo: 'Mogu li ići?',
    legalCallEmbassy: 'Želim nazvati svoje veleposlanstvo.',
    scriptLostSquad: 'Izgubio sam prijatelje. Mogu li koristiti vaš telefon ili Wi-Fi?',
    scriptSubstance: 'Moj prijatelj je nešto uzeo i treba mu pomoć. Bez policije, molim.',
    scriptMedicalTent: 'Gdje je medicinski šator / zona za dobrobit?',
    scriptCharging: 'Mobitel mi je prazan. Gdje je stanica za punjenje?',
  },
  {
    name: 'Kappa FuturFestival', city: 'Turin', country: 'Italy',
    startDate: '2026-07-03', endDate: '2026-07-05', lat: 45.091, lng: 7.675,
    vibe: 'Industrial Techno', camping: false, attendance: 90_000, language: 'Italian',
    medicalDoctor: 'Ho bisogno di un dottore.',
    medicalAllergy: 'Sono allergico alla penicillina.',
    legalFreeToGo: 'Posso andare?',
    legalCallEmbassy: 'Voglio chiamare la mia ambasciata.',
    scriptLostSquad: 'Ho perso i miei amici. Posso usare il tuo telefono o il Wi-Fi?',
    scriptSubstance: 'Il mio amico ha preso qualcosa e ha bisogno di aiuto. Niente polizia, per favore.',
    scriptMedicalTent: "Dov'è la tenda medica / l'area benessere?",
    scriptCharging: 'Il mio telefono si sta scaricando. Dov\'è la ricarica?',
  },
  {
    name: 'Parcels of Sound', city: 'Lisbon', country: 'Portugal',
    startDate: '2026-07-09', endDate: '2026-07-11', lat: 38.698, lng: -9.204,
    vibe: 'Alternative/Indie', camping: false, attendance: 30_000, language: 'Portuguese',
    medicalDoctor: 'Preciso de um médico.',
    medicalAllergy: 'Sou alérgico à penicilina.',
    legalFreeToGo: 'Estou livre para ir?',
    legalCallEmbassy: 'Quero ligar para a minha embaixada.',
    scriptLostSquad: 'Perdi os meus amigos. Posso usar o seu telemóvel ou Wi-Fi?',
    scriptSubstance: 'O meu amigo tomou algo e precisa de ajuda. Sem polícia, por favor.',
    scriptMedicalTent: 'Onde fica a tenda médica?',
    scriptCharging: 'Onde fica o posto de carregamento?',
  },
  {
    name: 'Ultra Europe', city: 'Split', country: 'Croatia',
    startDate: '2026-07-10', endDate: '2026-07-12', lat: 43.521, lng: 16.442,
    vibe: 'EDM/House', camping: false, attendance: 150_000, language: 'Croatian',
    medicalDoctor: 'Trebam liječnika.',
    medicalAllergy: 'Alergičan sam na penicilin.',
    legalFreeToGo: 'Mogu li ići?',
    legalCallEmbassy: 'Želim nazvati svoje veleposlanstvo.',
    scriptLostSquad: 'Izgubio sam prijatelje. Mogu li koristiti vaš telefon ili Wi-Fi?',
    scriptSubstance: 'Moj prijatelj je nešto uzeo i treba mu pomoć. Bez policije, molim.',
    scriptMedicalTent: 'Gdje je medicinski šator / zona za dobrobit?',
    scriptCharging: 'Mobitel mi je prazan. Gdje je stanica za punjenje?',
  },
  {
    name: 'TRNSMT', city: 'Glasgow', country: 'UK',
    startDate: '2026-07-10', endDate: '2026-07-12', lat: 55.850, lng: -4.240,
    vibe: 'Indie/Rock', camping: false, attendance: 50_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Wireless Festival', city: 'London', country: 'UK',
    startDate: '2026-07-10', endDate: '2026-07-12', lat: 51.571, lng: -0.096,
    vibe: 'Hip-Hop/Rap', camping: false, attendance: 50_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Tomorrowland (W1)', city: 'Boom', country: 'Belgium',
    startDate: '2026-07-17', endDate: '2026-07-19', lat: 51.091, lng: 4.368,
    vibe: 'Mainstream EDM', camping: true, attendance: 200_000, language: 'Dutch/French',
    medicalDoctor: 'Dokter nodig / Besoin d\'un docteur.',
    medicalAllergy: 'Allergie penicilline.',
    legalFreeToGo: 'Mag ik gaan? / Puis-je partir?',
    legalCallEmbassy: 'Ambassade bellen / Appeler l\'ambassade.',
    scriptLostSquad: 'Vrienden kwijt / Perdu mes amis.',
    scriptSubstance: 'Hulp nodig, geen politie / Aide, pas de police.',
    scriptMedicalTent: 'EHBO / Tente médicale?',
    scriptCharging: 'Opladen / Charge?',
  },
  {
    name: 'Parookaville', city: 'Weeze', country: 'Germany',
    startDate: '2026-07-17', endDate: '2026-07-19', lat: 51.602, lng: 6.142,
    vibe: 'Electronic City', camping: true, attendance: 210_000, language: 'German',
    medicalDoctor: 'Ich brauche einen Arzt.',
    medicalAllergy: 'Ich bin allergisch gegen Penicillin.',
    legalFreeToGo: 'Darf ich gehen?',
    legalCallEmbassy: 'Ich möchte meine Botschaft anrufen.',
    scriptLostSquad: 'Ich habe meine Freunde verloren. Kann ich Ihr Telefon oder WLAN benutzen?',
    scriptSubstance: 'Mein Freund hat etwas genommen und braucht Hilfe. Bitte keine Polizei.',
    scriptMedicalTent: 'Wo ist das Sanitätszelt / der Welfare-Bereich?',
    scriptCharging: 'Ich brauche eine Ladestation.',
  },
  {
    name: 'Elrow Town London', city: 'London', country: 'UK',
    startDate: '2026-07-18', endDate: '2026-07-19', lat: 51.515, lng: 0.015,
    vibe: 'Theatrical/House', camping: false, attendance: 25_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Latitude Festival', city: 'Southwold', country: 'UK',
    startDate: '2026-07-23', endDate: '2026-07-26', lat: 52.348, lng: 1.597,
    vibe: 'Arts/Indie', camping: true, attendance: 40_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Tomorrowland (W2)', city: 'Boom', country: 'Belgium',
    startDate: '2026-07-24', endDate: '2026-07-26', lat: 51.091, lng: 4.368,
    vibe: 'Mainstream EDM', camping: true, attendance: 200_000, language: 'Dutch/French',
    medicalDoctor: 'Dokter nodig / Besoin d\'un docteur.',
    medicalAllergy: 'Allergie penicilline.',
    legalFreeToGo: 'Mag ik gaan? / Puis-je partir?',
    legalCallEmbassy: 'Ambassade bellen / Appeler l\'ambassade.',
    scriptLostSquad: 'Vrienden kwijt / Perdu mes amis.',
    scriptSubstance: 'Hulp nodig, geen politie / Aide, pas de police.',
    scriptMedicalTent: 'EHBO / Tente médicale?',
    scriptCharging: 'Opladen / Charge?',
  },
  {
    name: 'Junction 2', city: 'London', country: 'UK',
    startDate: '2026-07-24', endDate: '2026-07-26', lat: 51.492, lng: -0.301,
    vibe: 'Techno/Progressive', camping: false, attendance: 25_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Wilderness Festival', city: 'Oxfordshire', country: 'UK',
    startDate: '2026-07-30', endDate: '2026-08-02', lat: 51.848, lng: -1.458,
    vibe: 'Boutique/Luxury', camping: true, attendance: 20_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Boardmasters', city: 'Newquay', country: 'UK',
    startDate: '2026-08-05', endDate: '2026-08-09', lat: 50.435, lng: -5.034,
    vibe: 'Surf/Electronic', camping: true, attendance: 50_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Untold Festival', city: 'Cluj-Napoca', country: 'Romania',
    startDate: '2026-08-06', endDate: '2026-08-09', lat: 46.768, lng: 23.572,
    vibe: 'Stadium EDM', camping: false, attendance: 470_000, language: 'Romanian',
    medicalDoctor: 'Am nevoie de un doctor.',
    medicalAllergy: 'Sunt alergic la penicilină.',
    legalFreeToGo: 'Sunt liber să plec?',
    legalCallEmbassy: 'Vreau să-mi sun ambasada.',
    scriptLostSquad: 'Mi-am pierdut prietenii.',
    scriptSubstance: 'Prietenul meu are nevoie de ajutor. Fără poliție.',
    scriptMedicalTent: 'Unde este cortul medical?',
    scriptCharging: 'Unde este stația de încărcare?',
  },
  {
    name: 'Lollapalooza Chicago', city: 'Chicago', country: 'USA',
    startDate: '2026-08-06', endDate: '2026-08-09', lat: 41.872, lng: -87.619,
    vibe: 'Multi-genre', camping: false, attendance: 460_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Houghton Festival', city: 'Norfolk', country: 'UK',
    startDate: '2026-08-06', endDate: '2026-08-09', lat: 52.825, lng: 0.658,
    vibe: 'Underground/Electronic', camping: true, attendance: 10_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Sziget Festival', city: 'Budapest', country: 'Hungary',
    startDate: '2026-08-11', endDate: '2026-08-15', lat: 47.553, lng: 19.055,
    vibe: 'Multi-genre', camping: true, attendance: 416_000, language: 'Hungarian',
    medicalDoctor: 'Orvosra van szükségem.',
    medicalAllergy: 'Allergiás vagyok a penicillinre.',
    legalFreeToGo: 'Szabadon távozhatok?',
    legalCallEmbassy: 'Szeretném felhívni a nagykövetségemet.',
    scriptLostSquad: 'Elvesztettem a barátaimat.',
    scriptSubstance: 'A barátom bevett valamit. Ne hívjanak rendőrt.',
    scriptMedicalTent: 'Hol van az orvosi sátor?',
    scriptCharging: 'Hol van a töltőállomás?',
  },
  {
    name: 'Boomtown Fair', city: 'Winchester', country: 'UK',
    startDate: '2026-08-12', endDate: '2026-08-16', lat: 51.086, lng: -1.243,
    vibe: 'Immersive/DnB', camping: true, attendance: 76_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'All Points East', city: 'London', country: 'UK',
    startDate: '2026-08-14', endDate: '2026-08-23', lat: 51.536, lng: -0.038,
    vibe: 'Alternative/Indie', camping: false, attendance: 50_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Green Man', city: 'Brecon Beacons', country: 'UK',
    startDate: '2026-08-20', endDate: '2026-08-23', lat: 51.859, lng: -3.161,
    vibe: 'Folk/Indie', camping: true, attendance: 20_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Creamfields', city: 'Cheshire', country: 'UK',
    startDate: '2026-08-27', endDate: '2026-08-30', lat: 53.337, lng: -2.614,
    vibe: 'Hard Dance/EDM', camping: true, attendance: 70_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Reading Festival', city: 'Reading', country: 'UK',
    startDate: '2026-08-27', endDate: '2026-08-30', lat: 51.464, lng: -0.985,
    vibe: 'Rock/Alternative', camping: true, attendance: 105_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Leeds Festival', city: 'Leeds', country: 'UK',
    startDate: '2026-08-27', endDate: '2026-08-30', lat: 53.867, lng: -1.372,
    vibe: 'Rock/Alternative', camping: true, attendance: 105_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Lost Village', city: 'Lincolnshire', country: 'UK',
    startDate: '2026-08-27', endDate: '2026-08-30', lat: 53.165, lng: -0.638,
    vibe: 'Boutique/Techno', camping: true, attendance: 15_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Shambala', city: 'Northamptonshire', country: 'UK',
    startDate: '2026-08-27', endDate: '2026-08-30', lat: 52.427, lng: -0.957,
    vibe: 'Creative/Eco', camping: true, attendance: 15_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
  {
    name: 'Tomorrowland Thailand', city: 'Chonburi', country: 'Thailand',
    startDate: '2026-12-11', endDate: '2026-12-13', lat: 12.898, lng: 100.985,
    vibe: 'Fantasy EDM', camping: true, attendance: 150_000, language: 'Thai',
    medicalDoctor: 'ฉันต้องการหมอ (Chǎn dtâung-gaan mǎu)',
    medicalAllergy: 'ฉันแพ้ยาเพนิซิลลิน (Chǎn pháe yaa pay-nee-sil-lin)',
    legalFreeToGo: 'ฉันไปได้หรือยัง? (Chǎn bpai dâai rǔu yang?)',
    legalCallEmbassy: 'ฉันต้องการโทรหาสถานทูต (Chǎn dtâung-gaan tō hǎa sà-thǎan-thôot)',
    scriptLostSquad: 'ฉันหลงกับเพื่อน ขอใช้โทรศัพท์หรือไวไฟได้ไหม (Chǎn lǒng gàp pêuuan. Kǎu chái tō-rá-sàp rǔu wai-fai dâai mǎi?)',
    scriptSubstance: 'เพื่อนฉันกินบางอย่างเข้าไปและต้องการความช่วยเหลือ โปรดอย่าเรียกตำรวจ (Pêuuan chǎn gin baang yàang khâo bpai... bpròat yàa rîak dtam-rùat)',
    scriptMedicalTent: 'เต็นท์พยาบาล / โซนสวัสดิการ อยู่ที่ไหน (Dten phá-yaa-baan / sōn sà-wàt-dì-gaan yùu thîe nǎi?)',
    scriptCharging: 'แบตโทรศัพท์กำลังจะหมด ที่ชาร์จอยู่ที่ไหน (Bàet tō-rá-sàp gam-lang jà mòt. Thîe cháat yùu thîe nǎi?)',
  },
  {
    name: 'Wonderfruit', city: 'Pattaya', country: 'Thailand',
    startDate: '2026-12-11', endDate: '2026-12-13', lat: 12.909, lng: 101.004,
    vibe: 'Eco/Boutique', camping: true, attendance: 25_000, language: 'Thai',
    medicalDoctor: 'ฉันต้องการหมอ (Chǎn dtâung-gaan mǎu)',
    medicalAllergy: 'ฉันแพ้ยาเพนิซิลลิน (Chǎn pháe yaa pay-nee-sil-lin)',
    legalFreeToGo: 'ฉันไปได้หรือยัง? (Chǎn bpai dâai rǔu yang?)',
    legalCallEmbassy: 'ฉันต้องการโทรหาสถานทูต (Chǎn dtâung-gaan tō hǎa sà-thǎan-thôot)',
    scriptLostSquad: 'ฉันหลงกับเพื่อน ขอใช้โทรศัพท์หรือไวไฟได้ไหม (Chǎn lǒng gàp pêuuan. Kǎu chái tō-rá-sàp rǔu wai-fai dâai mǎi?)',
    scriptSubstance: 'เพื่อนฉันกินบางอย่างเข้าไปและต้องการความช่วยเหลือ โปรดอย่าเรียกตำรวจ (Pêuuan chǎn gin baang yàang khâo bpai... bpròat yàa rîak dtam-rùat)',
    scriptMedicalTent: 'เต็นท์พยาบาล / โซนสวัสดิการ อยู่ที่ไหน (Dten phá-yaa-baan / sōn sà-wàt-dì-gaan yùu thîe nǎi?)',
    scriptCharging: 'แบตโทรศัพท์กำลังจะหมด ที่ชาร์จอยู่ที่ไหน (Bàet tō-rá-sàp gam-lang jà mòt. Thîe cháat yùu thîe nǎi?)',
  },
  {
    name: 'Beyond The Valley', city: 'Barunah Plains', country: 'Australia',
    startDate: '2026-12-28', endDate: '2027-01-01', lat: -38.118, lng: 143.911,
    vibe: 'Multi-genre', camping: true, attendance: 30_000, language: 'English',
    medicalDoctor: 'I need a doctor.',
    medicalAllergy: 'I am allergic to penicillin.',
    legalFreeToGo: 'Am I free to go?',
    legalCallEmbassy: 'I want to call my embassy.',
    scriptLostSquad: 'I have lost my friends. Can I use your phone or Wi-Fi?',
    scriptSubstance: 'My friend has taken something and needs help. No police, please.',
    scriptMedicalTent: 'Where is the medical tent / welfare area?',
    scriptCharging: 'My phone is dying. Where is the charging station?',
  },
];

// ── Seed Function ─────────────────────────────────────────────────────────────

/**
 * Imports all 50 CSV festivals into WatermelonDB on first install.
 * Safe to call on every app start — exits immediately if any festivals exist.
 * Completely offline — no network calls, no spinners.
 */
export async function seedFestivalsFromCSV(db: Database): Promise<void> {
  const existingCount = await db.get<Festival>('festivals').query().fetchCount();
  if (existingCount > 0) return;

  await db.write(async () => {
    await Promise.all(
      CSV_FESTIVALS.map((f) =>
        db.get<Festival>('festivals').create((r) => {
          r.festivalName = f.name;
          r.city = f.city;
          r.country = f.country;
          r.startDate = new Date(f.startDate).getTime();
          r.endDate = new Date(f.endDate).getTime();
          r.lat = f.lat;
          r.lng = f.lng;
          r.trigger = inferTrigger(f.vibe, f.camping);
          r.isAttending = false;
          r.vibe = f.vibe;
          r.camping = f.camping;
          r.expectedAttendance = f.attendance;
          r.primaryLanguage = f.language;
          r.medicalDoctor = f.medicalDoctor;
          r.medicalAllergy = f.medicalAllergy;
          r.legalFreeToGo = f.legalFreeToGo;
          r.legalCallEmbassy = f.legalCallEmbassy;
          r.scriptLostSquad = f.scriptLostSquad;
          r.scriptSubstance = f.scriptSubstance;
          r.scriptMedicalTent = f.scriptMedicalTent;
          r.scriptCharging = f.scriptCharging;
          r.safetyScore = computeSafetyScore(f.country, f.attendance, f.camping);
        })
      )
    );
  });
}
